

image: busybox:latest

before_script:
  - export WORKSPACE=$(pwd)
  - echo "$WORKSPACE"
  - export SNOWFLAKE_PASSWORD=$SF_PASSWORD

after_script:
  - echo ""

build:
  stage: build
  image: python:latest
  script:
    - python --version
    - pip install schemachange
  
test_variable:
  stage: test
  script:
    - echo "$SF_ACCOUNT"
    - echo "$SF_USERNAME"
    - echo "$SF_ROLE"
    - echo "$SF_WAREHOUSE"
    - echo "$SF_DATABASE"

running_schemachange:
  stage: deploy
  script:
    - echo "running schemachange"
    - schemachange -f $(pwd)/migrations/ -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table